sudo: required

arch:
  repos:
  packages:
    # pacman packages
    - archiso
  script:
    - "sudo ./build.sh -v"
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
